import Head from 'next/head'
import { Layout } from '../components/layout'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout title="Home Page">
        <p>Conteúdo da home page</p>
      </Layout>

    </div>
  )
}
